name: Redwood Build API Check
on:
  push:
    paths:
      - '/api/**/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Build Redwood API
        with:
          node-version: 17
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
        run: yarn rw build api
